// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package matcher is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	GetOrderBookRequest
	GetOrderBookResponse
*/
package matcher

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetOrderBookRequest struct {
}

func (m *GetOrderBookRequest) Reset()                    { *m = GetOrderBookRequest{} }
func (m *GetOrderBookRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOrderBookRequest) ProtoMessage()               {}
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetOrderBookResponse struct {
}

func (m *GetOrderBookResponse) Reset()                    { *m = GetOrderBookResponse{} }
func (m *GetOrderBookResponse) String() string            { return proto.CompactTextString(m) }
func (*GetOrderBookResponse) ProtoMessage()               {}
func (*GetOrderBookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*GetOrderBookRequest)(nil), "matcher.GetOrderBookRequest")
	proto.RegisterType((*GetOrderBookResponse)(nil), "matcher.GetOrderBookResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MatcherService service

type MatcherServiceClient interface {
	GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error)
}

type matcherServiceClient struct {
	cc *grpc.ClientConn
}

func NewMatcherServiceClient(cc *grpc.ClientConn) MatcherServiceClient {
	return &matcherServiceClient{cc}
}

func (c *matcherServiceClient) GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error) {
	out := new(GetOrderBookResponse)
	err := grpc.Invoke(ctx, "/matcher.MatcherService/GetOrderBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MatcherService service

type MatcherServiceServer interface {
	GetOrderBook(context.Context, *GetOrderBookRequest) (*GetOrderBookResponse, error)
}

func RegisterMatcherServiceServer(s *grpc.Server, srv MatcherServiceServer) {
	s.RegisterService(&_MatcherService_serviceDesc, srv)
}

func _MatcherService_GetOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatcherServiceServer).GetOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matcher.MatcherService/GetOrderBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatcherServiceServer).GetOrderBook(ctx, req.(*GetOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MatcherService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "matcher.MatcherService",
	HandlerType: (*MatcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderBook",
			Handler:    _MatcherService_GetOrderBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2c, 0x49, 0xce,
	0x48, 0x2d, 0x52, 0x12, 0xe5, 0x12, 0x76, 0x4f, 0x2d, 0xf1, 0x2f, 0x4a, 0x49, 0x2d, 0x72, 0xca,
	0xcf, 0xcf, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x12, 0xe3, 0x12, 0x41, 0x15, 0x2e,
	0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x35, 0x8a, 0xe7, 0xe2, 0xf3, 0x85, 0xe8, 0x0c, 0x86, 0x98, 0x27,
	0xe4, 0xcb, 0xc5, 0x83, 0xac, 0x52, 0x48, 0x46, 0x0f, 0x6a, 0xb4, 0x1e, 0x16, 0x73, 0xa5, 0x64,
	0x71, 0xc8, 0x42, 0x8c, 0x57, 0x62, 0x48, 0x62, 0x03, 0xbb, 0xcf, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xf3, 0x2f, 0x93, 0xa2, 0xb0, 0x00, 0x00, 0x00,
}
