// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exchange.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	exchange.proto

It has these top-level messages:
	Order
	TradeEvent
	OrderBookEvent
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type TradingPair int32

const (
	TradingPair_TRADING_PAIR_UNKNOWN TradingPair = 0
	TradingPair_BTC_USD              TradingPair = 1
	TradingPair_BTC_THB              TradingPair = 2
)

var TradingPair_name = map[int32]string{
	0: "TRADING_PAIR_UNKNOWN",
	1: "BTC_USD",
	2: "BTC_THB",
}
var TradingPair_value = map[string]int32{
	"TRADING_PAIR_UNKNOWN": 0,
	"BTC_USD":              1,
	"BTC_THB":              2,
}

func (x TradingPair) String() string {
	return proto1.EnumName(TradingPair_name, int32(x))
}
func (TradingPair) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Order_Type int32

const (
	Order_TYPE_UNKNOWN Order_Type = 0
	Order_MARKET       Order_Type = 1
	Order_LIMIT        Order_Type = 2
	Order_CANCEL       Order_Type = 3
)

var Order_Type_name = map[int32]string{
	0: "TYPE_UNKNOWN",
	1: "MARKET",
	2: "LIMIT",
	3: "CANCEL",
}
var Order_Type_value = map[string]int32{
	"TYPE_UNKNOWN": 0,
	"MARKET":       1,
	"LIMIT":        2,
	"CANCEL":       3,
}

func (x Order_Type) String() string {
	return proto1.EnumName(Order_Type_name, int32(x))
}
func (Order_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type OrderBookEvent_Type int32

const (
	OrderBookEvent_TYPE_UNKNOWN OrderBookEvent_Type = 0
	OrderBookEvent_ADD          OrderBookEvent_Type = 1
	OrderBookEvent_REMOVE       OrderBookEvent_Type = 2
)

var OrderBookEvent_Type_name = map[int32]string{
	0: "TYPE_UNKNOWN",
	1: "ADD",
	2: "REMOVE",
}
var OrderBookEvent_Type_value = map[string]int32{
	"TYPE_UNKNOWN": 0,
	"ADD":          1,
	"REMOVE":       2,
}

func (x OrderBookEvent_Type) String() string {
	return proto1.EnumName(OrderBookEvent_Type_name, int32(x))
}
func (OrderBookEvent_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type Order struct {
	OrderId   string                     `protobuf:"bytes,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Type      Order_Type                 `protobuf:"varint,3,opt,name=type,enum=proto.Order_Type" json:"type,omitempty"`
	IsSell    bool                       `protobuf:"varint,4,opt,name=is_sell,json=isSell" json:"is_sell,omitempty"`
	Price     float64                    `protobuf:"fixed64,5,opt,name=price" json:"price,omitempty"`
	Volume    float64                    `protobuf:"fixed64,6,opt,name=volume" json:"volume,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto1.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Order) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Order) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Order) GetType() Order_Type {
	if m != nil {
		return m.Type
	}
	return Order_TYPE_UNKNOWN
}

func (m *Order) GetIsSell() bool {
	if m != nil {
		return m.IsSell
	}
	return false
}

func (m *Order) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

type TradeEvent struct {
	OrderId       string                     `protobuf:"bytes,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	Timestamp     *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	IsTaker       bool                       `protobuf:"varint,3,opt,name=is_taker,json=isTaker" json:"is_taker,omitempty"`
	IsSell        bool                       `protobuf:"varint,4,opt,name=is_sell,json=isSell" json:"is_sell,omitempty"`
	Price         float64                    `protobuf:"fixed64,5,opt,name=price" json:"price,omitempty"`
	MatchedVolume float64                    `protobuf:"fixed64,6,opt,name=matched_volume,json=matchedVolume" json:"matched_volume,omitempty"`
	LeftVolume    float64                    `protobuf:"fixed64,7,opt,name=left_volume,json=leftVolume" json:"left_volume,omitempty"`
}

func (m *TradeEvent) Reset()                    { *m = TradeEvent{} }
func (m *TradeEvent) String() string            { return proto1.CompactTextString(m) }
func (*TradeEvent) ProtoMessage()               {}
func (*TradeEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TradeEvent) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *TradeEvent) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *TradeEvent) GetIsTaker() bool {
	if m != nil {
		return m.IsTaker
	}
	return false
}

func (m *TradeEvent) GetIsSell() bool {
	if m != nil {
		return m.IsSell
	}
	return false
}

func (m *TradeEvent) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TradeEvent) GetMatchedVolume() float64 {
	if m != nil {
		return m.MatchedVolume
	}
	return 0
}

func (m *TradeEvent) GetLeftVolume() float64 {
	if m != nil {
		return m.LeftVolume
	}
	return 0
}

type OrderBookEvent struct {
	OrderId   string                     `protobuf:"bytes,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Type      OrderBookEvent_Type        `protobuf:"varint,3,opt,name=type,enum=proto.OrderBookEvent_Type" json:"type,omitempty"`
	IsSell    bool                       `protobuf:"varint,4,opt,name=is_sell,json=isSell" json:"is_sell,omitempty"`
	Price     float64                    `protobuf:"fixed64,5,opt,name=price" json:"price,omitempty"`
	Volume    float64                    `protobuf:"fixed64,6,opt,name=volume" json:"volume,omitempty"`
}

func (m *OrderBookEvent) Reset()                    { *m = OrderBookEvent{} }
func (m *OrderBookEvent) String() string            { return proto1.CompactTextString(m) }
func (*OrderBookEvent) ProtoMessage()               {}
func (*OrderBookEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OrderBookEvent) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderBookEvent) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *OrderBookEvent) GetType() OrderBookEvent_Type {
	if m != nil {
		return m.Type
	}
	return OrderBookEvent_TYPE_UNKNOWN
}

func (m *OrderBookEvent) GetIsSell() bool {
	if m != nil {
		return m.IsSell
	}
	return false
}

func (m *OrderBookEvent) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderBookEvent) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func init() {
	proto1.RegisterType((*Order)(nil), "proto.Order")
	proto1.RegisterType((*TradeEvent)(nil), "proto.TradeEvent")
	proto1.RegisterType((*OrderBookEvent)(nil), "proto.OrderBookEvent")
	proto1.RegisterEnum("proto.TradingPair", TradingPair_name, TradingPair_value)
	proto1.RegisterEnum("proto.Order_Type", Order_Type_name, Order_Type_value)
	proto1.RegisterEnum("proto.OrderBookEvent_Type", OrderBookEvent_Type_name, OrderBookEvent_Type_value)
}

func init() { proto1.RegisterFile("exchange.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xc1, 0x6e, 0x9b, 0x40,
	0x14, 0xec, 0x62, 0x03, 0xf6, 0x73, 0x6b, 0xd1, 0x55, 0xd4, 0x12, 0x5f, 0x82, 0x2c, 0x45, 0x42,
	0x95, 0x4a, 0xa4, 0xf4, 0x52, 0xa9, 0x27, 0x6c, 0xa3, 0x16, 0x25, 0xc6, 0xd6, 0x66, 0x93, 0xaa,
	0x27, 0x44, 0xcc, 0x8b, 0xb3, 0x0a, 0x36, 0x08, 0x48, 0xd4, 0x7c, 0x41, 0x0f, 0xfd, 0xdc, 0xfe,
	0x40, 0xb5, 0x8b, 0x9d, 0xc6, 0x87, 0x1e, 0x72, 0xf0, 0x09, 0x66, 0x98, 0x37, 0x4f, 0x6f, 0x18,
	0xe8, 0xe3, 0xcf, 0xc5, 0x6d, 0xb2, 0x5e, 0xa2, 0x57, 0x94, 0x79, 0x9d, 0x53, 0x5d, 0x3d, 0x06,
	0x47, 0xcb, 0x3c, 0x5f, 0x66, 0x78, 0xa2, 0xd0, 0xf5, 0xfd, 0xcd, 0x49, 0x2d, 0x56, 0x58, 0xd5,
	0xc9, 0xaa, 0x68, 0x74, 0xc3, 0x5f, 0x1a, 0xe8, 0xb3, 0x32, 0xc5, 0x92, 0x1e, 0x42, 0x27, 0x97,
	0x2f, 0xb1, 0x48, 0x6d, 0xe2, 0x10, 0xb7, 0xcb, 0x4c, 0x85, 0xc3, 0x94, 0x7e, 0x86, 0xee, 0xd3,
	0x9c, 0xad, 0x39, 0xc4, 0xed, 0x9d, 0x0e, 0xbc, 0xc6, 0xd9, 0xdb, 0x3a, 0x7b, 0x7c, 0xab, 0x60,
	0xff, 0xc4, 0xf4, 0x18, 0xda, 0xf5, 0x63, 0x81, 0x76, 0xcb, 0x21, 0x6e, 0xff, 0xf4, 0x6d, 0xa3,
	0xf6, 0xd4, 0x42, 0x8f, 0x3f, 0x16, 0xc8, 0xd4, 0x67, 0xfa, 0x1e, 0x4c, 0x51, 0xc5, 0x15, 0x66,
	0x99, 0xdd, 0x76, 0x88, 0xdb, 0x61, 0x86, 0xa8, 0x2e, 0x30, 0xcb, 0xe8, 0x01, 0xe8, 0x45, 0x29,
	0x16, 0x68, 0xeb, 0x0e, 0x71, 0x09, 0x6b, 0x00, 0x7d, 0x07, 0xc6, 0x43, 0x9e, 0xdd, 0xaf, 0xd0,
	0x36, 0x14, 0xbd, 0x41, 0xc3, 0x2f, 0xd0, 0x96, 0xa6, 0xd4, 0x82, 0xd7, 0xfc, 0xc7, 0x3c, 0x88,
	0x2f, 0xa3, 0xb3, 0x68, 0xf6, 0x3d, 0xb2, 0x5e, 0x51, 0x00, 0x63, 0xea, 0xb3, 0xb3, 0x80, 0x5b,
	0x84, 0x76, 0x41, 0x3f, 0x0f, 0xa7, 0x21, 0xb7, 0x34, 0x49, 0x8f, 0xfd, 0x68, 0x1c, 0x9c, 0x5b,
	0xad, 0xe1, 0x1f, 0x02, 0xc0, 0xcb, 0x24, 0xc5, 0xe0, 0x01, 0xd7, 0xf5, 0x7e, 0xe2, 0x38, 0x84,
	0x8e, 0xa8, 0xe2, 0x3a, 0xb9, 0xc3, 0x52, 0x45, 0xd2, 0x61, 0xa6, 0xa8, 0xb8, 0x84, 0x2f, 0x8d,
	0xe0, 0x18, 0xfa, 0xab, 0xa4, 0x5e, 0xdc, 0x62, 0x1a, 0xef, 0x44, 0xf1, 0x66, 0xc3, 0x5e, 0x29,
	0x92, 0x1e, 0x41, 0x2f, 0xc3, 0x9b, 0x7a, 0xab, 0x31, 0x95, 0x06, 0x24, 0xd5, 0x08, 0x86, 0xbf,
	0x35, 0xe8, 0xab, 0xdf, 0x31, 0xca, 0xf3, 0xbb, 0x3d, 0x5e, 0xee, 0xed, 0x14, 0x61, 0xf0, 0xbc,
	0x08, 0x4f, 0x9b, 0xf7, 0xd0, 0x88, 0x8f, 0xff, 0x6d, 0x84, 0x09, 0x2d, 0x7f, 0x32, 0xb1, 0x88,
	0xec, 0x00, 0x0b, 0xa6, 0xb3, 0xab, 0xc0, 0xd2, 0x3e, 0xf8, 0xd0, 0x93, 0x15, 0x10, 0xeb, 0xe5,
	0x3c, 0x11, 0x25, 0xb5, 0xe1, 0x80, 0x33, 0x7f, 0x12, 0x46, 0x5f, 0xe3, 0xb9, 0x1f, 0xb2, 0x67,
	0xd3, 0x3d, 0x30, 0x47, 0x7c, 0x1c, 0x5f, 0x5e, 0x48, 0x87, 0x0d, 0xe0, 0xdf, 0x46, 0x96, 0x76,
	0x6d, 0xa8, 0xcb, 0x3e, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x31, 0x2b, 0xe2, 0xc5, 0x91, 0x03,
	0x00, 0x00,
}
