// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exchange.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	exchange.proto

It has these top-level messages:
	OrderInfo
	Order
	MatchedOrder
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type TradingPair int32

const (
	TradingPair_TRADING_PAIR_UNKNOWN TradingPair = 0
	TradingPair_BTC_USD              TradingPair = 1
	TradingPair_BTC_THB              TradingPair = 2
)

var TradingPair_name = map[int32]string{
	0: "TRADING_PAIR_UNKNOWN",
	1: "BTC_USD",
	2: "BTC_THB",
}
var TradingPair_value = map[string]int32{
	"TRADING_PAIR_UNKNOWN": 0,
	"BTC_USD":              1,
	"BTC_THB":              2,
}

func (x TradingPair) String() string {
	return proto1.EnumName(TradingPair_name, int32(x))
}
func (TradingPair) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type OrderType int32

const (
	OrderType_TYPE_UNKNOWN OrderType = 0
	OrderType_MARKET       OrderType = 1
	OrderType_LIMIT        OrderType = 2
	OrderType_CANCEL       OrderType = 3
)

var OrderType_name = map[int32]string{
	0: "TYPE_UNKNOWN",
	1: "MARKET",
	2: "LIMIT",
	3: "CANCEL",
}
var OrderType_value = map[string]int32{
	"TYPE_UNKNOWN": 0,
	"MARKET":       1,
	"LIMIT":        2,
	"CANCEL":       3,
}

func (x OrderType) String() string {
	return proto1.EnumName(OrderType_name, int32(x))
}
func (OrderType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Position int32

const (
	Position_POSITION_UNKNOWN Position = 0
	Position_BID              Position = 1
	Position_ASK              Position = 2
)

var Position_name = map[int32]string{
	0: "POSITION_UNKNOWN",
	1: "BID",
	2: "ASK",
}
var Position_value = map[string]int32{
	"POSITION_UNKNOWN": 0,
	"BID":              1,
	"ASK":              2,
}

func (x Position) String() string {
	return proto1.EnumName(Position_name, int32(x))
}
func (Position) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type OrderInfo struct {
	OrderId   string                     `protobuf:"bytes,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Type      OrderType                  `protobuf:"varint,4,opt,name=type,enum=proto.OrderType" json:"type,omitempty"`
	Position  Position                   `protobuf:"varint,5,opt,name=position,enum=proto.Position" json:"position,omitempty"`
}

func (m *OrderInfo) Reset()                    { *m = OrderInfo{} }
func (m *OrderInfo) String() string            { return proto1.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()               {}
func (*OrderInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OrderInfo) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderInfo) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *OrderInfo) GetType() OrderType {
	if m != nil {
		return m.Type
	}
	return OrderType_TYPE_UNKNOWN
}

func (m *OrderInfo) GetPosition() Position {
	if m != nil {
		return m.Position
	}
	return Position_POSITION_UNKNOWN
}

type Order struct {
	OrderInfo *OrderInfo `protobuf:"bytes,1,opt,name=order_info,json=orderInfo" json:"order_info,omitempty"`
	Price     float64    `protobuf:"fixed64,2,opt,name=price" json:"price,omitempty"`
	Volume    float64    `protobuf:"fixed64,3,opt,name=volume" json:"volume,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto1.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Order) GetOrderInfo() *OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

func (m *Order) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

type MatchedOrder struct {
	OrderInfo     *OrderInfo `protobuf:"bytes,1,opt,name=order_info,json=orderInfo" json:"order_info,omitempty"`
	MatchedPrice  float64    `protobuf:"fixed64,2,opt,name=matched_price,json=matchedPrice" json:"matched_price,omitempty"`
	MatchedVolume float64    `protobuf:"fixed64,3,opt,name=matched_volume,json=matchedVolume" json:"matched_volume,omitempty"`
	LeftVolume    float64    `protobuf:"fixed64,4,opt,name=left_volume,json=leftVolume" json:"left_volume,omitempty"`
}

func (m *MatchedOrder) Reset()                    { *m = MatchedOrder{} }
func (m *MatchedOrder) String() string            { return proto1.CompactTextString(m) }
func (*MatchedOrder) ProtoMessage()               {}
func (*MatchedOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MatchedOrder) GetOrderInfo() *OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

func (m *MatchedOrder) GetMatchedPrice() float64 {
	if m != nil {
		return m.MatchedPrice
	}
	return 0
}

func (m *MatchedOrder) GetMatchedVolume() float64 {
	if m != nil {
		return m.MatchedVolume
	}
	return 0
}

func (m *MatchedOrder) GetLeftVolume() float64 {
	if m != nil {
		return m.LeftVolume
	}
	return 0
}

func init() {
	proto1.RegisterType((*OrderInfo)(nil), "proto.OrderInfo")
	proto1.RegisterType((*Order)(nil), "proto.Order")
	proto1.RegisterType((*MatchedOrder)(nil), "proto.MatchedOrder")
	proto1.RegisterEnum("proto.TradingPair", TradingPair_name, TradingPair_value)
	proto1.RegisterEnum("proto.OrderType", OrderType_name, OrderType_value)
	proto1.RegisterEnum("proto.Position", Position_name, Position_value)
}

func init() { proto1.RegisterFile("exchange.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x8f, 0x9a, 0x40,
	0x14, 0xc6, 0x3b, 0x2a, 0x2a, 0x0f, 0x6b, 0x27, 0x13, 0xd3, 0xd0, 0xbd, 0xac, 0xb1, 0x6d, 0x62,
	0x6c, 0x82, 0x89, 0xbd, 0xf4, 0x58, 0x74, 0x4d, 0x3b, 0x71, 0x45, 0x32, 0xce, 0xb6, 0xe9, 0x89,
	0xb0, 0x32, 0xb0, 0x24, 0xc2, 0x10, 0x96, 0x6d, 0xba, 0xff, 0x53, 0x6f, 0xfd, 0x07, 0x1b, 0x06,
	0xb0, 0x7a, 0xed, 0x89, 0x7c, 0x1f, 0xbf, 0xf7, 0xbe, 0xf7, 0x78, 0xc0, 0x50, 0xfc, 0x3a, 0x3c,
	0xf8, 0x69, 0x24, 0xac, 0x2c, 0x97, 0x85, 0x24, 0x9a, 0x7a, 0x5c, 0x5d, 0x47, 0x52, 0x46, 0x47,
	0x31, 0x57, 0xea, 0xfe, 0x29, 0x9c, 0x17, 0x71, 0x22, 0x1e, 0x0b, 0x3f, 0xc9, 0x2a, 0x6e, 0xf2,
	0x07, 0x81, 0xbe, 0xcb, 0x03, 0x91, 0xd3, 0x34, 0x94, 0xe4, 0x0d, 0xf4, 0x65, 0x29, 0xbc, 0x38,
	0x30, 0xd1, 0x18, 0x4d, 0x75, 0xd6, 0x53, 0x9a, 0x06, 0xe4, 0x13, 0xe8, 0xa7, 0x5a, 0xb3, 0x35,
	0x46, 0x53, 0x63, 0x71, 0x65, 0x55, 0xdd, 0xad, 0xa6, 0xbb, 0xc5, 0x1b, 0x82, 0xfd, 0x83, 0xc9,
	0x3b, 0xe8, 0x14, 0xcf, 0x99, 0x30, 0x3b, 0x63, 0x34, 0x1d, 0x2e, 0x70, 0x45, 0x5b, 0x2a, 0x94,
	0x3f, 0x67, 0x82, 0xa9, 0xb7, 0xe4, 0x03, 0xf4, 0x33, 0xf9, 0x18, 0x17, 0xb1, 0x4c, 0x4d, 0x4d,
	0x91, 0xaf, 0x6a, 0xd2, 0xad, 0x6d, 0x76, 0x02, 0x26, 0x21, 0x68, 0xaa, 0x9e, 0xcc, 0x01, 0xea,
	0x81, 0xd3, 0x50, 0xaa, 0x91, 0x8d, 0xcb, 0x84, 0x72, 0x2d, 0xa6, 0xcb, 0xd3, 0x86, 0x23, 0xd0,
	0xb2, 0x3c, 0x3e, 0x08, 0xb5, 0x02, 0x62, 0x95, 0x20, 0xaf, 0xa1, 0xfb, 0x53, 0x1e, 0x9f, 0x12,
	0x61, 0xb6, 0x95, 0x5d, 0xab, 0xc9, 0x6f, 0x04, 0x83, 0xad, 0x5f, 0x1c, 0x1e, 0x44, 0xf0, 0x9f,
	0x79, 0x6f, 0xe1, 0x65, 0x52, 0x35, 0xf0, 0xce, 0x73, 0x07, 0xb5, 0xe9, 0xaa, 0xf8, 0xf7, 0x30,
	0x6c, 0xa0, 0x8b, 0x31, 0x9a, 0xd2, 0x6f, 0xca, 0x24, 0xd7, 0x60, 0x1c, 0x45, 0x58, 0x34, 0x4c,
	0x47, 0x31, 0x50, 0x5a, 0x15, 0x30, 0xb3, 0xc1, 0xe0, 0xb9, 0x1f, 0xc4, 0x69, 0xe4, 0xfa, 0x71,
	0x4e, 0x4c, 0x18, 0x71, 0x66, 0xdf, 0x50, 0xe7, 0x8b, 0xe7, 0xda, 0x94, 0x79, 0x77, 0xce, 0xc6,
	0xd9, 0x7d, 0x77, 0xf0, 0x0b, 0x62, 0x40, 0x6f, 0xc9, 0x57, 0xde, 0xdd, 0xfe, 0x06, 0xa3, 0x46,
	0xf0, 0xaf, 0x4b, 0xdc, 0x9a, 0x7d, 0xae, 0x7f, 0x87, 0xf2, 0x32, 0x04, 0xc3, 0x80, 0xff, 0x70,
	0xd7, 0x67, 0x85, 0x00, 0xdd, 0xad, 0xcd, 0x36, 0x6b, 0x8e, 0x11, 0xd1, 0x41, 0xbb, 0xa5, 0x5b,
	0xca, 0x71, 0xab, 0xb4, 0x57, 0xb6, 0xb3, 0x5a, 0xdf, 0xe2, 0xf6, 0x6c, 0x01, 0xfd, 0xe6, 0x62,
	0x64, 0x04, 0xd8, 0xdd, 0xed, 0x29, 0xa7, 0x3b, 0xe7, 0xac, 0x49, 0x0f, 0xda, 0x4b, 0x5a, 0x26,
	0xf7, 0xa0, 0x6d, 0xef, 0x37, 0xb8, 0x75, 0xdf, 0x55, 0x5f, 0xf0, 0xe3, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x20, 0xe9, 0xe7, 0x6b, 0xc6, 0x02, 0x00, 0x00,
}
