CREATE DATABASE IF NOT EXISTS TBox
	CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE TBox;

CREATE TABLE IF NOT EXISTS Users (
	UserId BIGINT NOT NULL AUTO_INCREMENT,
	UserName VARCHAR(255) NOT NULL,
	CreationTime DATETIME NOT NULL,
	PRIMARY KEY (UserId),
	UNIQUE (UserName)
) ENGINE = InnoDB;
