// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/catortiger/exchange/matching_engine/rpc/proto/service.proto

/*
Package matcherservice is a generated protocol buffer package.

It is generated from these files:
	github.com/catortiger/exchange/matching_engine/rpc/proto/service.proto

It has these top-level messages:
	GetOrderBookRequest
	GetOrderBookResponse
	CreateOrderRequest
	CreateOrderResponse
*/
package matcherservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import matcher "github.com/catortiger/exchange/matching_engine/matcher/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetOrderBookRequest struct {
	TradingPair matcher.TradingPair `protobuf:"varint,1,opt,name=trading_pair,json=tradingPair,enum=matcher.TradingPair" json:"trading_pair,omitempty"`
}

func (m *GetOrderBookRequest) Reset()                    { *m = GetOrderBookRequest{} }
func (m *GetOrderBookRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOrderBookRequest) ProtoMessage()               {}
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetOrderBookRequest) GetTradingPair() matcher.TradingPair {
	if m != nil {
		return m.TradingPair
	}
	return matcher.TradingPair_TRADING_PAIR_UNKNOWN
}

type GetOrderBookResponse struct {
	OrderBook *matcher.OrderBook `protobuf:"bytes,1,opt,name=order_book,json=orderBook" json:"order_book,omitempty"`
}

func (m *GetOrderBookResponse) Reset()                    { *m = GetOrderBookResponse{} }
func (m *GetOrderBookResponse) String() string            { return proto.CompactTextString(m) }
func (*GetOrderBookResponse) ProtoMessage()               {}
func (*GetOrderBookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetOrderBookResponse) GetOrderBook() *matcher.OrderBook {
	if m != nil {
		return m.OrderBook
	}
	return nil
}

type CreateOrderRequest struct {
	TradingPair matcher.TradingPair `protobuf:"varint,1,opt,name=trading_pair,json=tradingPair,enum=matcher.TradingPair" json:"trading_pair,omitempty"`
	Order       *matcher.Order      `protobuf:"bytes,2,opt,name=order" json:"order,omitempty"`
}

func (m *CreateOrderRequest) Reset()                    { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()               {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateOrderRequest) GetTradingPair() matcher.TradingPair {
	if m != nil {
		return m.TradingPair
	}
	return matcher.TradingPair_TRADING_PAIR_UNKNOWN
}

func (m *CreateOrderRequest) GetOrder() *matcher.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type CreateOrderResponse struct {
	TradeEvents     []*matcher.TradeEvent     `protobuf:"bytes,1,rep,name=trade_events,json=tradeEvents" json:"trade_events,omitempty"`
	OrderBookEvents []*matcher.OrderBookEvent `protobuf:"bytes,2,rep,name=order_book_events,json=orderBookEvents" json:"order_book_events,omitempty"`
}

func (m *CreateOrderResponse) Reset()                    { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()               {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateOrderResponse) GetTradeEvents() []*matcher.TradeEvent {
	if m != nil {
		return m.TradeEvents
	}
	return nil
}

func (m *CreateOrderResponse) GetOrderBookEvents() []*matcher.OrderBookEvent {
	if m != nil {
		return m.OrderBookEvents
	}
	return nil
}

func init() {
	proto.RegisterType((*GetOrderBookRequest)(nil), "matcherservice.GetOrderBookRequest")
	proto.RegisterType((*GetOrderBookResponse)(nil), "matcherservice.GetOrderBookResponse")
	proto.RegisterType((*CreateOrderRequest)(nil), "matcherservice.CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "matcherservice.CreateOrderResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MatcherService service

type MatcherServiceClient interface {
	GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
}

type matcherServiceClient struct {
	cc *grpc.ClientConn
}

func NewMatcherServiceClient(cc *grpc.ClientConn) MatcherServiceClient {
	return &matcherServiceClient{cc}
}

func (c *matcherServiceClient) GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error) {
	out := new(GetOrderBookResponse)
	err := grpc.Invoke(ctx, "/matcherservice.MatcherService/GetOrderBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matcherServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := grpc.Invoke(ctx, "/matcherservice.MatcherService/CreateOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MatcherService service

type MatcherServiceServer interface {
	GetOrderBook(context.Context, *GetOrderBookRequest) (*GetOrderBookResponse, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
}

func RegisterMatcherServiceServer(s *grpc.Server, srv MatcherServiceServer) {
	s.RegisterService(&_MatcherService_serviceDesc, srv)
}

func _MatcherService_GetOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatcherServiceServer).GetOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matcherservice.MatcherService/GetOrderBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatcherServiceServer).GetOrderBook(ctx, req.(*GetOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatcherService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatcherServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matcherservice.MatcherService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatcherServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MatcherService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "matcherservice.MatcherService",
	HandlerType: (*MatcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderBook",
			Handler:    _MatcherService_GetOrderBook_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _MatcherService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/catortiger/exchange/matching_engine/rpc/proto/service.proto",
}

func init() {
	proto.RegisterFile("github.com/catortiger/exchange/matching_engine/rpc/proto/service.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x4d, 0x45, 0xc1, 0x49, 0x89, 0xb8, 0x2d, 0x58, 0x7a, 0x2a, 0x69, 0x0f, 0x3d, 0x25,
	0x18, 0x41, 0xef, 0x16, 0x15, 0x05, 0xff, 0x50, 0x3d, 0x08, 0x1e, 0xca, 0x36, 0x1d, 0xd2, 0xa5,
	0x34, 0x1b, 0x67, 0xb7, 0xc5, 0xe7, 0xf0, 0xa5, 0x7c, 0x2d, 0xe9, 0x6e, 0x62, 0x1a, 0x2b, 0x05,
	0xf1, 0xb6, 0xb3, 0xf3, 0x7d, 0xbf, 0x6f, 0xff, 0x0c, 0x5c, 0x25, 0x42, 0x4f, 0x17, 0xe3, 0x20,
	0x96, 0xf3, 0x30, 0xe6, 0x5a, 0x92, 0x16, 0x09, 0x52, 0x88, 0xef, 0xf1, 0x94, 0xa7, 0x09, 0x86,
	0x73, 0xae, 0xe3, 0xa9, 0x48, 0x93, 0x11, 0xa6, 0x89, 0x48, 0x31, 0xa4, 0x2c, 0x0e, 0x33, 0x92,
	0x5a, 0x86, 0x0a, 0x69, 0x29, 0x62, 0x0c, 0x4c, 0xc5, 0x3c, 0x23, 0x44, 0xca, 0x77, 0xdb, 0xb7,
	0x7f, 0xe4, 0xe6, 0xf6, 0x9c, 0x9d, 0x57, 0x96, 0xed, 0xdf, 0x43, 0xe3, 0x1a, 0xf5, 0x03, 0x4d,
	0x90, 0x2e, 0xa4, 0x9c, 0x0d, 0xf1, 0x6d, 0x81, 0x4a, 0xb3, 0x73, 0xa8, 0x6b, 0xe2, 0x93, 0x15,
	0x24, 0xe3, 0x82, 0x5a, 0x4e, 0xc7, 0xe9, 0x7b, 0x51, 0x33, 0x28, 0xcc, 0xcf, 0xb6, 0xf9, 0xc8,
	0x05, 0x0d, 0x5d, 0x5d, 0x16, 0xfe, 0x0d, 0x34, 0xab, 0x3c, 0x95, 0xc9, 0x54, 0x21, 0x3b, 0x01,
	0x90, 0xab, 0xcd, 0xd1, 0x58, 0xca, 0x99, 0xc1, 0xb9, 0x11, 0xfb, 0xc6, 0x95, 0xfa, 0x03, 0x59,
	0x2c, 0x7d, 0x05, 0x6c, 0x40, 0xc8, 0x35, 0x9a, 0xee, 0x7f, 0x4f, 0xc6, 0x7a, 0xb0, 0x67, 0xd8,
	0xad, 0x9a, 0x09, 0xf7, 0xaa, 0xe1, 0x43, 0xdb, 0xf4, 0x3f, 0x1c, 0x68, 0x54, 0x52, 0xf3, 0xf3,
	0x9f, 0xd9, 0x58, 0x1c, 0xe1, 0x12, 0x53, 0xad, 0x5a, 0x4e, 0x67, 0xb7, 0xef, 0x46, 0x8d, 0x4a,
	0x2c, 0x5e, 0xae, 0x7a, 0x36, 0xd5, 0xae, 0x15, 0x1b, 0xc0, 0x51, 0x79, 0xef, 0xc2, 0x5c, 0x33,
	0xe6, 0xe3, 0xcd, 0xeb, 0x5b, 0xc0, 0xa1, 0xac, 0xd4, 0x2a, 0xfa, 0x74, 0xc0, 0xbb, 0xb3, 0xda,
	0x27, 0x3b, 0x03, 0xec, 0x15, 0xea, 0xeb, 0xef, 0xcc, 0xba, 0x41, 0x75, 0x48, 0x82, 0x5f, 0x7e,
	0xb5, 0xdd, 0xdb, 0x2e, 0xb2, 0x57, 0xf5, 0x77, 0xd8, 0x0b, 0xb8, 0x6b, 0x6f, 0xc0, 0xfc, 0x9f,
	0xb6, 0xcd, 0x6f, 0x69, 0x77, 0xb7, 0x6a, 0x0a, 0xf2, 0x78, 0xdf, 0x4c, 0xdd, 0xe9, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x51, 0xff, 0x87, 0xcd, 0x1b, 0x03, 0x00, 0x00,
}
